### ISSUE TITLE
Update the GSTT-CSC organisation homepage

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/gstt-csc-old#49]
Homepage looks a bit bare. Suggest adding the CSC logo as the profile image and something like the following for bio:

Clinical Scientific Computing, Guy's and St Thomas' NHS Foundation Trust
[gstt-csc.github.io](url)

CSC logo file:

![transparent-CSC-logo](https://user-images.githubusercontent.com/33687657/123769898-ad236d80-d8c1-11eb-9c33-48dad2f31212.png)

**Comment by hshuaib90** [comment]
Have updated - what do you think? The logo is too big to fit fully. I've even resized it down to 1/3 of its original size but GitHub still thinks it's the same size?

**Comment by laurencejackson** [comment]
Yeah, looks like it will only accept a square logo! Could you try downloading and using the logo image attached below:

![CSC-logo-square](https://user-images.githubusercontent.com/33687657/125905189-055c483e-0a8a-40cb-bebb-5acb85abc084.png)

**Comment by hshuaib90** [comment]
It wasn't the squareness, it was actually the ratio of the logo size to the image size. I just made it smaller and it now fits!
