### ISSUE TITLE
CSC events and deadlines calendar 

### ISSUE THREAD

**Issue by AnilMistry** [GSTT-CSC/gstt-csc-old#51]
It would be useful for the website to have a calendar or list of important upcoming events relevant to the CSC. 
These could include:

- submission deadlines for relevant grant proposals
- important conferences and registration dates
- any other interesting events internally or externally

**Comment by hshuaib90** [comment]
Can we have everyone list relevant deadlines/events here, then we can make it into a page.

**Comment by simoambr** [comment]
Conferences
- RSNA - usually paper submission is in July (now open)
- ECR/ESR - usually paper submission is in July (now open), free for PhD students or Young Investigators

**Comment by lucy-funnell** [comment]
Ideas for showcasing successful deployments

- HSJ Awards (Acute Sector Innovation of the Year, Driving Efficiency through Technology Award) Submission deadline June.
- BMJ Awards (Diagnostics Team of the Year,  Digital Innovation Team of the Year, or Clinical area) December-June

**Comment by AnilMistry** [comment]
Estro 2021 - August 27th - August 31st (last tickets 27th July)
HTN Awards (https://htn.co.uk/health-tech-awards-2021/)
AI in Health and Care Awards https://www.nhsx.nhs.uk/ai-lab/ai-lab-programmes/ai-health-and-care-award/

**Comment by dangerdika** [comment]
XNAT virtual workshop, 13-14 September 2021 (free)

**Comment by dangerdika** [comment]
SIIM abstract deadline in 17th December. 
AI in Genomics by Royal Society of Medicine is on 24th November (organised by @alexandertdeng !)
Topol fellowship webinar is on 23rd November.

**Comment by tomaroberts** [comment]
Closing with new site release – CSC team members have autonomy to update calendar as they see fit.
