### ISSUE TITLE
Project template difficult to edit

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/gstt-csc-old#54]
This issue came about after I tried to add the project plan to an existing project in PR#53.

I've found it quite difficult to modify the markdown in the existing template. Currently, the project pages are one big markdown table and it can be awkward to add large sections (such as the project plan), since they do not allow newline characters, only HTML breaks. The markdown preview in pycharm and atom was also unable to properly preview the table in the same way as it appeared on the served website. 

To resolve this I added the project plan section in plain markdown after the table. This seems to be a much more practical way to write in this section and will make it easier in the future to add new details to the plan as they are agreed.

In this way the table because a sort of quick project overview with more detail in sections below.

- [ ] The current table should be a static component that is filled at the start of a project but things that are likely to evolve or be updated over the duration of a project should be placed after the table.

**Comment by laurencejackson** [comment]
[link to PR 53](https://github.com/GSTT-CSC/gstt-csc.github.io/pull/53)

**Comment by hshuaib90** [comment]
Closed by #75
