### ISSUE TITLE
Add images to wordy pages

### ISSUE THREAD

**Issue by AnilMistry** [GSTT-CSC/gstt-csc-old#66]
As the website expands with blog entries and 10X write-ups, we are seeing wordy pages which could be more readable with images to break up the walls of text. 

Images should be carefully chosen as not to infantalise the often serious issues we are discussing.

**Comment by hshuaib90** [comment]
Would it be a good idea to have some kind of template for people to follow? That could help remind people to include an image or two.

**Comment by AnilMistry** [comment]
That would be great. I agree a minimum one image per blog, Ideally two, or enought to break up walls of text. Also having an author profile picture (taken from our team page) on each blog page  would make it look more professional.

**Comment by tomaroberts** [comment]
Resolved by Blog template on new website. As discussed in Standup this morning, we should keep blogs to very short word counts (ie: 150 words or thereabouts.)
