### ISSUE TITLE
All titles repeat twice

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/gstt-csc-old#69]
The title of each page is written twice, once in the blue banner and once in the actual text. This is really weird and distracting, and its created by the markdown. Needs a change in css?

**Comment by alexandertdeng** [comment]
@dangerdika I cannot replicate this from my side, could you screenshot to demonstrate the problem?

**Comment by dangerdika** [comment]
@alexandertdeng The stand alone pages have it, such as this: https://gstt-csc.github.io/blogs/20210317-10x-Workshop1.html or this: https://gstt-csc.github.io/platforms/secure-enclave.html . Its because of the way markdown takes and applies the title both to the banner and the actual top of text

**Comment by alexandertdeng** [comment]
#82 Pull request is merged, this issue can be closed

**Comment by hshuaib90** [comment]
Thanks @alexandertdeng . In future, you can link an issue to a PR on the right hand side column of an issue, so when the PR merges the issue closes.
