### ISSUE TITLE
Add National Data Opt-Out information.

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/gstt-csc-old#99]
I would like to add "National Data Opt-Out" in the Kanban page under "Governance", which will link to further information on the [National Data Opt-Out (NDOO)](https://digital.nhs.uk/services/national-data-opt-out) policy on the website's Policy page. This will include links to the GTi (GSTT intranet) and NHS Digital NDOO webpages, NDOO check service, and Message Exchange for Social Care and Health (MESH) webpage, current policy compliance deadline, and response from Information Governance regarding existing projects.

**Comment by hshuaib90** [comment]
I don't think the Kanban board is the right place. That is for development work. The governance column indicates projects that are undergoing governance approval. Sorry if that's not clear!

What about under How-to/SOPs ? Or happy for you to suggest an alternative.

**Comment by tomaroberts** [comment]
@heyhaleema – can you close or transfer this issue to the new website repo. Thanks.

**Comment by heyhaleema** [comment]
I'll close both this issue and #100, and raise a new issue in the new website repo.
